//
//  CountriesViewModel.swift
//  SwiftUIStudy
//
//  Created by USER on 17.01.2024.
//

import Foundation

class CountriesViewModel: ObservableObject {
    @Published var countries: [CountryModel] = [
        CountryModel(name: "Argentina", continent: "South America", capital: "Buenos Aires", population: 43_417_000, description_small: "In 2004, I completed two Inuit art buying trips to Iqaluit, the capital of Nunavut, Canada’s newest territory. For both trips, I flew out of Ottawa on Canadian airlines.", description: "As long as humans can think, there will be wars. Wars over such concepts as freedom, honor, dignity, etc.. Wars over territory, greed, power, prejudice, etc.. War is a part of human nature. For example, every human being is prejudiced. If they don’t like some race, nationality or religion, they don’t like short or tall or fat or skinny or smart or not smart or loud or quiet people. Some people don’t like children, some people don’t like old people, some people don’t like people with pets, or people that play their music too loud, or bad drivers, or people that believe in God or people that don’t believe in God.", image: URL(string: "https://www.votpusk.ru/country/ctimages/new/AR01.jpg")!, country_info: CountryInfo(images: [], flag: URL(string: "http://flags.fmcdn.net/data/flags/w580/ar.png")!)),
        CountryModel(name: "Argentina", continent: "South America", capital: "Buenos Aires", population: 43_417_000, description_small: "In 2004, I completed two Inuit art buying trips to Iqaluit, the capital of Nunavut, Canada’s newest territory. For both trips, I flew out of Ottawa on Canadian airlines.", description: "As long as humans can think, there will be wars. Wars over such concepts as freedom, honor, dignity, etc.. Wars over territory, greed, power, prejudice, etc.. War is a part of human nature. For example, every human being is prejudiced. If they don’t like some race, nationality or religion, they don’t like short or tall or fat or skinny or smart or not smart or loud or quiet people. Some people don’t like children, some people don’t like old people, some people don’t like people with pets, or people that play their music too loud, or bad drivers, or people that believe in God or people that don’t believe in God.", image: URL(string: "https://www.votpusk.ru/country/ctimages/new/AR01.jpg")!, country_info: CountryInfo(images: [], flag: URL(string: "http://flags.fmcdn.net/data/flags/w580/ar.png")!)),
        CountryModel(name: "Argentina", continent: "South America", capital: "Buenos Aires", population: 43_417_000, description_small: "In 2004, I completed two Inuit art buying trips to Iqaluit, the capital of Nunavut, Canada’s newest territory. For both trips, I flew out of Ottawa on Canadian airlines.", description: "As long as humans can think, there will be wars. Wars over such concepts as freedom, honor, dignity, etc.. Wars over territory, greed, power, prejudice, etc.. War is a part of human nature. For example, every human being is prejudiced. If they don’t like some race, nationality or religion, they don’t like short or tall or fat or skinny or smart or not smart or loud or quiet people. Some people don’t like children, some people don’t like old people, some people don’t like people with pets, or people that play their music too loud, or bad drivers, or people that believe in God or people that don’t believe in God.", image: URL(string: "https://www.votpusk.ru/country/ctimages/new/AR01.jpg")!, country_info: CountryInfo(images: [], flag: URL(string: "http://flags.fmcdn.net/data/flags/w580/ar.png")!)),
        CountryModel(name: "Argentina", continent: "South America", capital: "Buenos Aires", population: 43_417_000, description_small: "In 2004, I completed two Inuit art buying trips to Iqaluit, the capital of Nunavut, Canada’s newest territory. For both trips, I flew out of Ottawa on Canadian airlines.", description: "As long as humans can think, there will be wars. Wars over such concepts as freedom, honor, dignity, etc.. Wars over territory, greed, power, prejudice, etc.. War is a part of human nature. For example, every human being is prejudiced. If they don’t like some race, nationality or religion, they don’t like short or tall or fat or skinny or smart or not smart or loud or quiet people. Some people don’t like children, some people don’t like old people, some people don’t like people with pets, or people that play their music too loud, or bad drivers, or people that believe in God or people that don’t believe in God.", image: URL(string: "https://www.votpusk.ru/country/ctimages/new/AR01.jpg")!, country_info: CountryInfo(images: [], flag: URL(string: "http://flags.fmcdn.net/data/flags/w580/ar.png")!)),
    ]
    
    func fetch() {
        let c = CountryModel(name: "Argentina", continent: "South America", capital: "Buenos Aires", population: 43_417_000, description_small: "In 2004, I completed two Inuit art buying trips to Iqaluit, the capital of Nunavut, Canada’s newest territory. For both trips, I flew out of Ottawa on Canadian airlines.", description: "As long as humans can think, there will be wars. Wars over such concepts as freedom, honor, dignity, etc.. Wars over territory, greed, power, prejudice, etc.. War is a part of human nature. For example, every human being is prejudiced. If they don’t like some race, nationality or religion, they don’t like short or tall or fat or skinny or smart or not smart or loud or quiet people. Some people don’t like children, some people don’t like old people, some people don’t like people with pets, or people that play their music too loud, or bad drivers, or people that believe in God or people that don’t believe in God.", image: URL(string: "https://www.votpusk.ru/country/ctimages/new/AR01.jpg")!, country_info: CountryInfo(images: [], flag: URL(string: "http://flags.fmcdn.net/data/flags/w580/ar.png")!))
        
        countries.append(c)
        countries.append(c)
        countries.append(c)
        countries.append(c)
    }
}
