name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  iOSTests:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Tests
        run: |
          xcodebuild test \
          -project SwiftUIStudy.xcodeproject \
          -scheme SwiftUIStudyTests \
          -destination 'platform=iOS Simulator, name=iPhone 15' \
          CODE_SIGNING_REQUIRED=NO
