name: iOS starter workflow

on: [push]

jobs:
  iOSTests:
    runs-on: macos-13
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      
      - name: Tests
        run: |
          xcodebuild test \
          -project SwiftUIStudy.xcodeproj \
          -scheme SwiftUIStudy \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -allowProvisioningUpdates
